[build-system]
requires = ["maturin>=1"]
build-backend = "maturin"

[project]
name = "bytewax"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: System :: Networking",
    "Topic :: System :: Distributed Computing",
]
dependencies = [
    "typing_extensions>=4",
    "prometheus-client>=0.18"
]

extras = [
    "cbfmt",
    "dev",
    "kafka",
    "test",
]

[project.optional-dependencies]
cbfmt = [
    "ruff==0.3.2",
]
dev = [
    "bytewax[cbfmt,kafka,test]",
    "astor==0.8.1 ; python_version <= '3.8'",
    "graphlib_backport==1.0.3 ; python_version <= '3.8'",
    "pre-commit==2.19.0",
    "ruff==0.3.2",
    "vermin==1.5.2",
]
kafka = [
    "requests>=2.0",
    "fastavro>=1.8",
    "confluent-kafka>=2.0.2",
]
test = [
    "myst-docutils==0.17.0",
    "pytest==7.4.0",
    "pytest-codspeed>=2.2",
    "pytest-benchmark>=3.4",
    "sybil==6.0.3",
]

[project.urls]
"Source Code" = "https://github.com/bytewax/bytewax"
Issues = "https://github.com/bytewax/bytewax/issues"
Documentation = "https://docs.bytewax.io/"
Changelog = "https://github.com/bytewax/bytewax/blob/main/CHANGELOG.md"

[metadata]
long_description = "file: README.md"
long_description_content_type = "text/markdown"

[tool.pytest.ini_options]
addopts = "-v -p no:doctest --benchmark-skip"
testpaths = [
    "docs",
    "pytests",
    "pysrc",
    "README.md",
]

[tool.maturin]
module-name = "bytewax._bytewax"
python-source = "pysrc"

[tool.mypy]
mypy_path = "pysrc"

[tool.ruff]
select = [
    "A",
    "B",
    "D",
    "DTZ",
    "E",
    "EM",
    "F",
    "I",
    "PL",
    "W",
]
ignore = [
    "D105",
    "E731",
    "PLR",
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.per-file-ignores]
"examples/*.py" = ["D"]
"pytests/test_flows/*.py" = ["D"]
"test_*.py" = ["D"]
# Because `test_encoder` has huge literals in it.
"pytests/test_encoder.py" = ["E501"]
